202331232_Uswatun Hasanah Hamado

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

NumPy (np): Digunakan untuk operasi matematika dan manipulasi array atau matriks multidimensi.
Pandas (pd): Digunakan untuk manipulasi dan analisis data, terutama dalam bentuk tabel seperti DataFrame.
Matplotlib (plt): Digunakan untuk membuat grafik dan visualisasi data.

In [3]:
dataset = pd.read_csv('K03_counter_strike_2.csv')
dataset

time_left  ct_score  t_score       map  bomb_planted  ct_health  \
0        175.00       0.0      0.0  de_dust2         False      500.0   
1        156.03       0.0      0.0  de_dust2         False      500.0   
2         96.03       0.0      0.0  de_dust2         False      391.0   
3         76.03       0.0      0.0  de_dust2         False      391.0   
4        174.97       1.0      0.0  de_dust2         False      500.0   
...         ...       ...      ...       ...           ...        ...   
1995      74.90       7.0     10.0  de_train         False      327.0   
1996      31.23       7.0     10.0  de_train          True      227.0   
1997      11.23       7.0     10.0  de_train          True      185.0   
1998     174.91       7.0     11.0  de_train         False      500.0   
1999     114.90       7.0     11.0  de_train         False      500.0   

      t_health  ct_armor  t_armor  ct_money  t_money  ct_helmets  t_helmets  \
0        500.0       0.0      0.0    4000.0   4000.0         0.0        0.0   
1        500.0     400.0    300.0     600.0    650.0         0.0        0.0   
2        400.0     294.0    200.0     750.0    500.0         0.0        0.0   
3        400.0     294.0    200.0     750.0    500.0         0.0        0.0   
4        500.0     192.0      0.0   18350.0  10750.0         0.0        0.0   
...        ...       ...      ...       ...      ...         ...        ...   
1995     355.0     376.0    183.0    6350.0  13300.0         3.0        1.0   
1996     152.0     276.0    183.0    5000.0   7900.0         2.0        1.0   
1997     105.0     266.0    183.0    5300.0   4450.0         2.0        1.0   
1998     500.0      55.0      0.0   14900.0  32000.0         0.0        0.0   
1999     500.0     355.0    500.0     650.0   6150.0         1.0        5.0   

     round_winner  
0              CT  
1              CT  
2              CT  
3              CT  
4              CT  
...           ...  
1995            T  
1996            T  
1997            T  
1998            T  
1999           CT  

[2000 rows x 14 columns]

Perintah dataset = pd.read_csv('K03_counter_strike_2.csv') digunakan untuk membaca file CSV dan menyimpannya dalam variabel dataset sebagai DataFrame. Untuk melihat data, kamu bisa menggunakan dataset.head() untuk menampilkan lima baris pertama.

In [4]:
dataset.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   time_left     2000 non-null   float64
 1   ct_score      2000 non-null   float64
 2   t_score       2000 non-null   float64
 3   map           2000 non-null   object 
 4   bomb_planted  2000 non-null   bool   
 5   ct_health     2000 non-null   float64
 6   t_health      2000 non-null   float64
 7   ct_armor      2000 non-null   float64
 8   t_armor       2000 non-null   float64
 9   ct_money      2000 non-null   float64
 10  t_money       2000 non-null   float64
 11  ct_helmets    2000 non-null   float64
 12  t_helmets     2000 non-null   float64
 13  round_winner  2000 non-null   object 
dtypes: bool(1), float64(11), object(2)
memory usage: 205.2+ KB


Perintah dataset.info() digunakan untuk menampilkan informasi tentang dataset, seperti:

Jumlah baris dan kolom.
Nama kolom dan tipe data masing-masing.
Jumlah nilai non-null (tidak kosong) pada setiap kolom.
Ini memberikan gambaran umum tentang struktur dataset.

In [5]:
categorical_features = [feature for feature in dataset.columns
                        if dataset[feature].dtypes == "O"]
dataset[categorical_features]

map round_winner
0     de_dust2           CT
1     de_dust2           CT
2     de_dust2           CT
3     de_dust2           CT
4     de_dust2           CT
...        ...          ...
1995  de_train            T
1996  de_train            T
1997  de_train            T
1998  de_train            T
1999  de_train           CT

[2000 rows x 2 columns]

Kode tersebut berfungsi untuk:

Membuat daftar categorical_features, yang berisi nama-nama kolom dalam dataset yang memiliki tipe data object (biasanya untuk data kategori atau teks).

dataset[categorical_features] kemudian menampilkan hanya kolom-kolom yang termasuk dalam daftar categorical_features.

Secara sederhana, ini digunakan untuk mengekstrak dan menampilkan kolom yang berisi data kategori (seperti string atau label).

In [6]:
for i in categorical_features:
    print(dataset[i].unique())

['de_dust2' 'de_mirage' 'de_nuke' 'de_inferno' 'de_overpass' 'de_vertigo'
 'de_train']
['CT' 'T']


Kode ini digunakan untuk menampilkan nilai unik yang ada dalam setiap kolom kategori (data tipe object) dalam dataset.

    for i in categorical_features: akan mengiterasi setiap kolom dalam daftar categorical_features.
    dataset[i].unique() akan menampilkan nilai-nilai unik (tanpa duplikasi) dari kolom i.
Dengan kode ini, kamu bisa melihat semua kategori yang terdapat dalam setiap kolom kategori dalam dataset.

In [7]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

for feature in categorical_features:
    print(dataset[feature].unique())
    dataset[feature] = label_encoder.fit_transform(dataset[feature])
    print(dataset[feature].unique())

['de_dust2' 'de_mirage' 'de_nuke' 'de_inferno' 'de_overpass' 'de_vertigo'
 'de_train']
[0 2 3 1 4 6 5]
['CT' 'T']
[0 1]


Kode ini menggunakan LabelEncoder dari pustaka scikit-learn untuk mengubah nilai kategori (teks) dalam kolom menjadi angka (label numerik):

LabelEncoder: Digunakan untuk mengubah data kategori menjadi angka, yang sering kali diperlukan untuk pemodelan mesin atau algoritma yang memerlukan data numerik.

for feature in categorical_features:: Mengiterasi setiap kolom yang ada dalam daftar categorical_features.

dataset[feature].unique(): Menampilkan nilai unik sebelum transformasi.

label_encoder.fit_transform(dataset[feature]): Mengonversi nilai kategori menjadi angka dan mengganti kolom tersebut dengan nilai yang sudah terkodekan.

dataset[feature].unique(): Menampilkan nilai unik setelah transformasi, yang sekarang berupa angka.

Dengan cara ini, kolom kategori dalam dataset akan diubah menjadi format numerik yang siap digunakan dalam analisis atau pemodelan.

In [8]:
dataset

time_left  ct_score  t_score  map  bomb_planted  ct_health  t_health  \
0        175.00       0.0      0.0    0         False      500.0     500.0   
1        156.03       0.0      0.0    0         False      500.0     500.0   
2         96.03       0.0      0.0    0         False      391.0     400.0   
3         76.03       0.0      0.0    0         False      391.0     400.0   
4        174.97       1.0      0.0    0         False      500.0     500.0   
...         ...       ...      ...  ...           ...        ...       ...   
1995      74.90       7.0     10.0    5         False      327.0     355.0   
1996      31.23       7.0     10.0    5          True      227.0     152.0   
1997      11.23       7.0     10.0    5          True      185.0     105.0   
1998     174.91       7.0     11.0    5         False      500.0     500.0   
1999     114.90       7.0     11.0    5         False      500.0     500.0   

      ct_armor  t_armor  ct_money  t_money  ct_helmets  t_helmets  \
0          0.0      0.0    4000.0   4000.0         0.0        0.0   
1        400.0    300.0     600.0    650.0         0.0        0.0   
2        294.0    200.0     750.0    500.0         0.0        0.0   
3        294.0    200.0     750.0    500.0         0.0        0.0   
4        192.0      0.0   18350.0  10750.0         0.0        0.0   
...        ...      ...       ...      ...         ...        ...   
1995     376.0    183.0    6350.0  13300.0         3.0        1.0   
1996     276.0    183.0    5000.0   7900.0         2.0        1.0   
1997     266.0    183.0    5300.0   4450.0         2.0        1.0   
1998      55.0      0.0   14900.0  32000.0         0.0        0.0   
1999     355.0    500.0     650.0   6150.0         1.0        5.0   

      round_winner  
0                0  
1                0  
2                0  
3                0  
4                0  
...            ...  
1995             1  
1996             1  
1997             1  
1998             1  
1999             0  

[2000 rows x 14 columns]

In [11]:
x = dataset.drop(['map', 'round_winner'], axis = 1)
y = dataset['round_winner']

Kode ini memisahkan dataset menjadi dua bagian:

x: Fitur, dengan menghapus kolom map dan round_winner.
y: Target, yang berisi kolom round_winner.

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25,random_state = 0)

Kode ini digunakan untuk membagi dataset menjadi data latih (training) dan data uji (test):

train_test_split(x, y, test_size=0.25, random_state=0):
x: Fitur (independent variables).
y: Target (dependent variable).
test_size=0.25: 25% dari data akan digunakan untuk uji, sisanya 75% untuk latih.
random_state=0: Menetapkan nilai acak agar pembagian data konsisten setiap kali kode dijalankan.
Hasilnya:

x_train, y_train: Data latih untuk fitur dan target.
x_test, y_test: Data uji untuk fitur dan target.

In [13]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

Kode ini digunakan untuk melatih model Naive Bayes menggunakan algoritma Gaussian Naive Bayes:

        from sklearn.naive_bayes import GaussianNB: Mengimpor model Gaussian Naive Bayes dari pustaka scikit-learn.
        
        model = GaussianNB(): Membuat objek model GaussianNB.
        
        model.fit(x_train, y_train): Melatih model menggunakan data latih (x_train untuk fitur dan y_train untuk target).

Model ini akan mempelajari hubungan antara fitur dan target untuk kemudian digunakan dalam prediksi pada data uji.

In [14]:
y_pred_train = model.predict(x_train)
y_pred_test = model.predict(x_test)

y_pred_train = model.predict(x_train): Menggunakan model untuk memprediksi target pada data latih (x_train), hasil prediksi disimpan dalam y_pred_train.

y_pred_test = model.predict(x_test): Menggunakan model untuk memprediksi target pada data uji (x_test), hasil prediksi disimpan dalam y_pred_test.

In [20]:
from sklearn.metrics import confusion_matrix, classification_report
print('evaluasi training')
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print('evaluasi testing')
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))

evaluasi training
[[390 223]
 [161 726]]
              precision    recall  f1-score   support

           0       0.71      0.64      0.67       613
           1       0.77      0.82      0.79       887

    accuracy                           0.74      1500
   macro avg       0.74      0.73      0.73      1500
weighted avg       0.74      0.74      0.74      1500

evaluasi testing
[[137  74]
 [ 55 234]]
              precision    recall  f1-score   support

           0       0.71      0.65      0.68       211
           1       0.76      0.81      0.78       289

    accuracy                           0.74       500
   macro avg       0.74      0.73      0.73       500
weighted avg       0.74      0.74      0.74       500



Kode ini digunakan untuk mengevaluasi kinerja model menggunakan metrik confusion matrix dan classification report:

confusion_matrix(y_train, y_pred_train): Menghitung dan menampilkan matriks kebingunguan (confusion matrix) untuk data latih. Matriks ini menunjukkan jumlah prediksi yang benar dan salah untuk setiap kelas pada data latih.

classification_report(y_train, y_pred_train): Menampilkan laporan klasifikasi yang mencakup metrik seperti precision, recall, f1-score, dan support untuk data latih.

confusion_matrix(y_test, y_pred_test): Menghitung dan menampilkan matriks kebingunguan untuk data uji.

classification_report(y_test, y_pred_test): Menampilkan laporan klasifikasi untuk data uji.

Dengan kode ini, kamu bisa mengevaluasi seberapa baik model memprediksi pada data latih dan data uji.